/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useMemo, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useLerp } from '../../utils/hooks';
import { Color } from 'three';

export default function CarModel({hex, ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/car.gltf');

	const bodyMaterial = materials.Body;
  const initialCol = useRef(bodyMaterial.color);
	const targetCol = useMemo(() => (hex ? new Color(hex) : initialCol.current), [hex]);
  const color = useLerp(bodyMaterial.color, targetCol);

  bodyMaterial.color = color;

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh007.geometry} material={bodyMaterial} />
        <mesh geometry={nodes.Mesh007_1.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Mesh007_2.geometry} material={materials['Front Lights']} />
        <mesh geometry={nodes.Mesh007_3.geometry} material={materials['Back Lights']} />
        <mesh geometry={nodes.Mesh007_4.geometry} material={materials.Black} />
        <mesh geometry={nodes.Mesh007_5.geometry} material={materials.FrontColor} />
      </group>
    </group>
  )
}

useGLTF.preload('/car.gltf')
